
### sign-up - Cadastro
POST http://localhost:3333/sign-up
Content-Type: application/json

{
  "name": "julio",
  "email": "julio@gmail.com",
  "password": "1234567"
}

### sign-in -login
POST http://localhost:3333/sign-in
Content-Type: application/json

{
  "email": "julio@gmail.com",
  "password": "1234567"
}



### profile

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyM2YwY2FhMi03ZDU3LTRmZWUtOGRlNS0xYjdjYzcwMmVmZTciLCJpYXQiOjE3NzMyNjU2NTksImV4cCI6MTc3MzM1MjA1OX0.881kNuA-6Pdwj3rADkkyLRzOo7B6j2YqBfW6sG3WZLQ
GET http://localhost:3333/me
Content-Type: application/json
Authorization: Bearer {{token}}
