
@baseUrl = http://localhost:3333

###

### sign-up - Cadastro
POST {{baseUrl}}/sign-up
Content-Type: application/json

{
  "name": "julio",
  "email": "julio@gmail.com",
  "password": "123456",
  "role": "USER"
}

### sign-in -login
POST {{baseUrl}}/sign-in
Content-Type: application/json

{
  "email": "julio@gmail.com",
  "password": "123456"
}



### profile

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlMzAzNWVjZS1kODE4LTQxNjItOTE1Mi01YTJlYWExNDk1NWIiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc4NzY3MTc1MCwiZXhwIjoxNzg3NzU4MTUwfQ.V-p_5wWSleMr0VcVqpW7hfxvWcj0bjKWs16UDUJdYJc

GET {{baseUrl}}/me
Content-Type: application/json
Authorization: Bearer {{token}}
