
### sign-up - Cadastro
POST http://localhost:3333/sign-up
Content-Type: application/json

{
  "name": "julio",
  "email": "julio@gmail.com",
  "password": "123456",
  "role": "USER"
}

### sign-in -login
POST http://localhost:3333/sign-in
Content-Type: application/json

{
  "email": "julio@gmail.com",
  "password": "123456"
}



### profile

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ZmU3OWJhOS1lMDc2LTRhNzItYWUxOC0xM2E5MTBkMzNiOGMiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc4NjM5NTA1MiwiZXhwIjoxNzg2NDgxNDUyfQ.MzLKozuUORxztoQhxHE9KelcPhHZwwdAw68NGgwJe-4
GET http://localhost:3333/me
Content-Type: application/json
Authorization: Bearer {{token}}
